name: sarj33t_login_btns

description: A Flutter package for both android and iOS which provides Social signin Buttons

version: 0.0.7

homepage: https://github.com/sarj33t-prakash/flutter-social-buttons

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/